name: Docker Build and Push

on:
  push:
    branches: [ "master", "staging", "production" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Set BUILD_ENV build arg
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "BUILD_ENV=production" >> $GITHUB_ENV
          else
            echo "BUILD_ENV=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login 
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.BUILD_ENV }}
            type=raw,value=latest
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            BUILD_ENV=${{ env.BUILD_ENV }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


